AWSTemplateFormatVersion: "2010-09-09"
Description: Template to create a EC2 Instance - based on env parameter, instance type selected, EIP assigned for PROD

Parameters:
  EnvSelector:
    Description: Please choose the environment
    Type: String
    AllowedValues:
      - dev
      - test
      - prod

Conditions:
  EIPforProd: !Equals [ !Ref EnvSelector, prod ]
 
Mappings:
  ImageBasedOnRegion:
    us-east-1:
      img: ami-09d069a04349dc3cb
    us-east-2:
      img: ami-02ccb28830b645a41
    us-west-1:
      img: ami-03caa3f860895f82e
    us-west-2:
      img: ami-04590e7389a6e577c
  InstanceTypeBasedOnEnv:
    dev:
      tname: t2.micro
    test:
      tname: t2.small
    prod:
      tname: t2.small
Resources:
  EC2Server:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap
        - ImageBasedOnRegion
        - !Ref 'AWS::Region'
        - img
      InstanceType: !FindInMap
        - InstanceTypeBasedOnEnv
        - !Ref EnvSelector
        - tname
      SecurityGroups:
        - default

  ProdServerEIP:
    Type: AWS::EC2::EIP
    Condition: EIPforProd
    Properties:
      InstanceId: !Ref EC2Server
    
